version: 2


models:
  - name: stg_btc
    columns:
      - name: HASHKEY
        tests:
          - not_null
          - unique
  - name: stg_btc_outputs
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('stg_btc_outputs_py')
  - name: whale_alert
    latest_version: 2
    config:
      contract:
        enforced: true
    columns:
      - name: total_sent
        data_type: float
      - name: tx_count
        data_type: int
      - name: total_sent_usd
        data_type: float
      - name: output_address
        data_tests:
          - assert_valid_btc_address
        data_type: string
    versions:
      - v: 1
        deprecation_date: 2026-03-01
        config:
          enabled: true
      - v: 2
        columns:
          - include: all
            exclude: [total_sent_usd]
  
exposures:

  - name: btc_whale_alert_exposure
    label: BTC Whale Alert
    type: dashboard
    maturity: high
    url: https://lookerstudio.google.com/u/2/reporting/186c64a4-b66f-446c-8b94-81adf6d44864/page/9nSpF/edit
    description: >
      BTC Whale alert transactions report

    depends_on:
      - ref('whale_alert', v=1)

    owner:
      name: Johannes Leeb